# Generated by Django 2.1.7 on 2019-02-28 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('birth_date', models.DateField(null=True)),
                ('death_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('number', models.IntegerField(null=True)),
                ('desc', models.TextField(blank=True)),
                ('publish_date', models.DateField()),
                ('main_cover', models.ImageField(null=True, upload_to='')),
                ('link', models.URLField(max_length=1000, unique=True)),
                ('pencilers', models.ManyToManyField(related_name='drawn_issues', to='comics_db.Creator')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='comics_db.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='TitleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='universes', to='comics_db.Publisher')),
            ],
        ),
        migrations.AddField(
            model_name='title',
            name='title_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='comics_db.TitleType'),
        ),
        migrations.AddField(
            model_name='title',
            name='universe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='comics_db.Universe'),
        ),
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(related_name='issues', to='comics_db.Tag'),
        ),
        migrations.AddField(
            model_name='issue',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='comics_db.Title'),
        ),
        migrations.AddField(
            model_name='issue',
            name='writers',
            field=models.ManyToManyField(related_name='written_issues', to='comics_db.Creator'),
        ),
        migrations.AlterUniqueTogether(
            name='universe',
            unique_together={('name', 'publisher')},
        ),
        migrations.AlterUniqueTogether(
            name='title',
            unique_together={('name', 'publisher', 'universe', 'title_type')},
        ),
        migrations.AlterUniqueTogether(
            name='issue',
            unique_together={('name', 'title', 'publish_date')},
        ),
    ]
