# Generated by Django 2.1.7 on 2019-03-01 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFilesParserRunDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Successfully ended'), ('ERROR', 'Error')], default='RUNNING', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('error_details', models.TextField(blank=True)),
                ('file_key', models.TextField()),
                ('regex', models.TextField()),
                ('groups', models.TextField(blank=True)),
                ('issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comics_db.Issue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParserRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser', models.CharField(max_length=30)),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Successfully ended'), ('ENDED_WITH_ERRORS', 'Ended with errors'), ('CRITICAL_ERROR', 'Critical Error'), ('INVALID_PARSER', 'Parser implementation is not valid')], default='RUNNING', max_length=30)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='cloudfilesparserrundetail',
            name='parser_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloudfilesparserrundetails', to='comics_db.ParserRun'),
        ),
    ]
