# Generated by Django 2.2 on 2019-06-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0001_squashed_0056_auto_20190423_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marvelevent',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='readinglist',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=500, unique=True),
        ),
    ]
