# Generated by Django 2.1.7 on 2019-03-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0002_auto_20190301_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserrun',
            name='parser',
            field=models.CharField(choices=[('BASE', 'Base parser'), ('CLOUD_FILES', 'Cloud files parser')], default='BASE', max_length=30),
        ),
    ]
