# Generated by Django 2.1.7 on 2019-03-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0003_auto_20190301_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserrun',
            name='items_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parserrun',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Successfully ended'), ('ENDED_WITH_ERRORS', 'Ended with errors'), ('CRITICAL_ERROR', 'Critical Error'), ('INVALID_PARSER', 'Invalid parser implementation')], default='RUNNING', max_length=30),
        ),
    ]
