# Generated by Django 2.2 on 2019-06-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0004_auto_20190602_0430'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='readinglistissue',
            order_with_respect_to='reading_list',
        ),
    ]
