# Generated by Django 2.2 on 2019-06-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0005_auto_20190602_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglistissue',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterOrderWithRespectTo(
            name='readinglistissue',
            order_with_respect_to=None,
        ),
    ]
