# Generated by Django 2.2 on 2019-06-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0006_auto_20190602_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='sorting',
            field=models.CharField(choices=[('DEFAULT', 'Order by title and issue number'), ('MANUAL', 'Manual ordering')], default='DEFAULT', max_length=20),
        ),
    ]
