# Generated by Django 2.1.7 on 2019-03-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0006_remove_cloudfilesparserrundetail_error_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudfilesparserrundetail',
            name='error_stack',
            field=models.TextField(blank=True),
        ),
    ]
