# Generated by Django 2.1.7 on 2019-03-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0007_cloudfilesparserrundetail_error_stack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudfilesparserrundetail',
            old_name='error_stack',
            new_name='error_detail',
        ),
        migrations.AddField(
            model_name='parserrun',
            name='error_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
