# Generated by Django 2.1.7 on 2019-03-01 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0008_auto_20190302_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
