# Generated by Django 2.2.1 on 2019-06-08 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0008_auto_20190606_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creator',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='marvelevent',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marvelevent',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='title',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='universe',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='universe',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
