# Generated by Django 2.2.1 on 2019-06-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0009_auto_20190608_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
    ]
