# Generated by Django 2.1.7 on 2019-03-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0009_auto_20190302_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserrun',
            name='processed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parserrun',
            name='items_count',
            field=models.IntegerField(default=1),
        ),
    ]
