# Generated by Django 2.1.7 on 2019-03-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0010_auto_20190302_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserrun',
            name='items_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parserrun',
            name='processed',
            field=models.IntegerField(null=True),
        ),
    ]
