# Generated by Django 2.2.1 on 2019-07-19 17:25

import comics_db.fields
import comics_db.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0010_issue_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='marvel_api_id',
        ),
        migrations.AddField(
            model_name='creator',
            name='image',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to=comics_db.models.get_creator_image_name),
        ),
        migrations.AddField(
            model_name='creator',
            name='url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='marvelapicreator',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marvel_api_creator', to='comics_db.Creator'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='photo',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to=comics_db.models.get_creator_photo_name),
        ),
        migrations.AlterField(
            model_name='parserrun',
            name='status',
            field=models.CharField(choices=[('COLLECTING', 'Collecting data'), ('RUNNING', 'Running'), ('SUCCESS', 'Successfully ended'), ('ENDED_WITH_ERRORS', 'Ended with errors'), ('API_THROTTLE', 'API rate limit has been surpassed.'), ('CRITICAL_ERROR', 'Critical Error'), ('INVALID_PARSER', 'Invalid parser implementation'), ('QUEUE', 'In queue')], default='COLLECTING', max_length=30),
        ),
        migrations.CreateModel(
            name='MarvelAPICreatorMergeParserRunDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='RUNNING', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created', models.BooleanField(default=False)),
                ('api_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.MarvelAPICreator')),
                ('db_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.Creator')),
                ('parser_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marvelapicreatormergeparserrundetails', to='comics_db.ParserRun')),
            ],
            options={
                'ordering': ['parser_run', '-start'],
                'abstract': False,
            },
        ),
    ]
