# Generated by Django 2.2.3 on 2019-07-19 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0011_auto_20190719_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marvelapicreatormergeparserrundetail',
            name='db_creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comics_db.Creator'),
        ),
        migrations.AlterField(
            model_name='marvelapiimage',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='comics_db.MarvelAPICharacter'),
        ),
        migrations.AlterField(
            model_name='marvelapiimage',
            name='comics',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='comics_db.MarvelAPIComics'),
        ),
        migrations.AlterField(
            model_name='marvelapiimage',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='comics_db.MarvelAPICreator'),
        ),
        migrations.AlterField(
            model_name='marvelapiimage',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='comics_db.MarvelAPIEvent'),
        ),
        migrations.AlterField(
            model_name='marvelapiimage',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='comics_db.MarvelAPISeries'),
        ),
        migrations.AlterField(
            model_name='parserrun',
            name='parser',
            field=models.CharField(choices=[('BASE', 'Base parser'), ('CLOUD_FILES', 'Cloud files parser'), ('MARVEL_API', 'Marvel API parser'), ('MARVEL_API_CREATOR_MERGE', 'Marvel API creator merge')], default='BASE', max_length=30),
        ),
    ]
