# Generated by Django 2.1.7 on 2019-03-03 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0011_auto_20190302_0146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['id']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='issue',
            order_with_respect_to='title',
        ),
    ]
