# Generated by Django 2.2.3 on 2019-07-19 23:28

import comics_db.fields
import comics_db.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0012_auto_20190719_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='marvel_api_id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='marvel_detail_link',
        ),
        migrations.AddField(
            model_name='character',
            name='marvel_wiki_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='character',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='comics_db.Publisher'),
        ),
        migrations.AddField(
            model_name='marvelapicharacter',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marvel_api_chararcter', to='comics_db.Character'),
        ),
        migrations.AlterField(
            model_name='character',
            name='image',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to=comics_db.models.get_character_image_name),
        ),
        migrations.AlterField(
            model_name='parserrun',
            name='parser',
            field=models.CharField(choices=[('BASE', 'Base parser'), ('CLOUD_FILES', 'Cloud files parser'), ('MARVEL_API', 'Marvel API parser'), ('MARVEL_API_CREATOR_MERGE', 'Marvel API creator merge'), ('MARVEL_API_CHARACTER_MERGE', 'Marvel API character merge')], default='BASE', max_length=30),
        ),
        migrations.CreateModel(
            name='MarvelAPICharacterMergeParserRunDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='RUNNING', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created', models.BooleanField(default=False)),
                ('api_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.MarvelAPICharacter')),
                ('db_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comics_db.Character')),
                ('parser_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marvelapicharactermergeparserrundetails', to='comics_db.ParserRun')),
            ],
            options={
                'ordering': ['parser_run', '-start'],
                'abstract': False,
            },
        ),
    ]
