# Generated by Django 2.1.7 on 2019-03-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0012_auto_20190303_0540'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='issue',
            order_with_respect_to=None,
        ),
    ]
