# Generated by Django 2.1.7 on 2019-03-03 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0013_auto_20190303_0616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['title', 'number']},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['publisher', 'universe', 'name']},
        ),
        migrations.AlterModelOptions(
            name='universe',
            options={'ordering': ['publisher', 'name']},
        ),
        migrations.AlterField(
            model_name='title',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='comics_db.Publisher'),
        ),
    ]
