# Generated by Django 2.2.3 on 2019-07-20 00:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0013_auto_20190720_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='event-image')),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=500, unique=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(related_name='events', to='comics_db.Character')),
                ('creators', models.ManyToManyField(related_name='events', to='comics_db.Creator')),
                ('issues', models.ManyToManyField(related_name='events', to='comics_db.Issue')),
                ('titles', models.ManyToManyField(related_name='events', to='comics_db.Title')),
            ],
        ),
        migrations.CreateModel(
            name='MarvelAPIEventMergeParserRunDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='RUNNING', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('created', models.BooleanField(default=False)),
                ('api_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.MarvelAPIEvent')),
                ('db_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comics_db.Event')),
            ],
            options={
                'ordering': ['parser_run', '-start'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='parserrun',
            name='parser',
            field=models.CharField(choices=[('BASE', 'Base parser'), ('CLOUD_FILES', 'Cloud files parser'), ('MARVEL_API', 'Marvel API parser'), ('MARVEL_API_CREATOR_MERGE', 'Marvel API creator merge'), ('MARVEL_API_CHARACTER_MERGE', 'Marvel API character merge'), ('MARVEL_API_EVENT_MERGE', 'Marvel API event merge')], default='BASE', max_length=30),
        ),
        migrations.DeleteModel(
            name='MarvelEvent',
        ),
        migrations.AddField(
            model_name='marvelapieventmergeparserrundetail',
            name='parser_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marvelapieventmergeparserrundetails', to='comics_db.ParserRun'),
        ),
        migrations.AddField(
            model_name='marvelapievent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marvel_api_event', to='comics_db.Event'),
        ),
    ]
