# Generated by Django 2.2.3 on 2019-07-20 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0014_auto_20190720_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='comics_db.Publisher'),
        ),
    ]
