# Generated by Django 2.1.7 on 2019-03-06 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0014_auto_20190303_0848'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cloudfilesparserrundetail',
            options={'ordering': ['parser_run', '-start']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['title', 'publish_date', 'number']},
        ),
        migrations.AlterModelOptions(
            name='parserrun',
            options={'ordering': ['-start']},
        ),
    ]
