# Generated by Django 2.2.3 on 2019-07-20 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0015_event_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='creators',
        ),
        migrations.AlterField(
            model_name='marvelapiimage',
            name='series',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image', to='comics_db.MarvelAPISeries'),
        ),
        migrations.CreateModel(
            name='EventCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.Creator')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.Event')),
            ],
        ),
    ]
