# Generated by Django 2.2.3 on 2019-07-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0016_auto_20190720_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creators',
            field=models.ManyToManyField(related_name='events', through='comics_db.EventCreator', to='comics_db.Creator'),
        ),
    ]
