# Generated by Django 2.1.7 on 2019-03-07 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0017_auto_20190307_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='parserrun',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='apptoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
