# Generated by Django 2.2.3 on 2019-07-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0017_event_creators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('publisher', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('publisher', 'name')},
        ),
    ]
