# Generated by Django 2.1.7 on 2019-03-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0018_auto_20190307_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudfilesparserrundetail',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='RUNNING', max_length=30),
        ),
    ]
