# Generated by Django 2.2.3 on 2019-07-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0018_auto_20190721_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvelapiseries',
            name='series_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
