# Generated by Django 2.1.7 on 2019-03-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0019_auto_20190308_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserRunParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('val', models.TextField(blank=True)),
                ('parser_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='comics_db.ParserRun')),
            ],
        ),
    ]
