# Generated by Django 2.1.7 on 2019-03-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0020_parserrunparameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parserrunparameter',
            name='parser_run',
        ),
        migrations.DeleteModel(
            name='ParserRunParameter',
        ),
    ]
