# Generated by Django 2.1.7 on 2019-03-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0021_auto_20190308_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
