# Generated by Django 2.2.3 on 2019-07-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0021_auto_20190721_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='marvel_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='title',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
