# Generated by Django 2.2.3 on 2019-07-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0022_auto_20190721_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titlecreator',
            old_name='issue',
            new_name='title',
        ),
    ]
