# Generated by Django 2.1.7 on 2019-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0022_publisher_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.ImageField(null=True, upload_to='publisher_logo'),
        ),
    ]
