# Generated by Django 2.2.3 on 2019-07-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0023_auto_20190723_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marvelapititlemergeparserrundetail',
            name='created',
        ),
    ]
