# Generated by Django 2.2.3 on 2019-07-29 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0024_remove_marvelapititlemergeparserrundetail_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='marvel_api_id',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='marvel_api_status',
        ),
        migrations.RemoveField(
            model_name='marvelapititlemergeparserrundetail',
            name='api_title',
        ),
        migrations.RemoveField(
            model_name='marvelapititlemergeparserrundetail',
            name='db_title',
        ),
        migrations.AddField(
            model_name='issue',
            name='marvel_api_comic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='db_issue', to='comics_db.MarvelAPIComics'),
        ),
        migrations.AddField(
            model_name='issue',
            name='possible_matches',
            field=models.ManyToManyField(null=True, related_name='db_possible_issues', to='comics_db.MarvelAPIComics'),
        ),
        migrations.AddField(
            model_name='marvelapititlemergeparserrundetail',
            name='api_comics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comics_db.MarvelAPIComics'),
        ),
        migrations.AddField(
            model_name='marvelapititlemergeparserrundetail',
            name='db_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comics_db.Issue'),
        ),
        migrations.AlterField(
            model_name='marvelapicomics',
            name='issue_number',
            field=models.FloatField(help_text='The number of the issue in the series (will generally be 0 for collection formats).', null=True),
        ),
        migrations.AlterField(
            model_name='marvelapititlemergeparserrundetail',
            name='merge_result',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('NOT_FOUND', 'Match not found'), ('DUPLICATES', 'Multiple matches'), ('MANUAL', 'Manually changed')], max_length=20),
        ),
        migrations.CreateModel(
            name='MarvelAPIIssueMergeParserRunDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='RUNNING', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('merge_result', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('NOT_FOUND', 'Match not found'), ('DUPLICATES', 'Multiple matches'), ('MANUAL', 'Manually changed')], max_length=20)),
                ('api_comic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comics_db.MarvelAPISeries')),
                ('db_issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comics_db.Title')),
                ('parser_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marvelapiissuemergeparserrundetails', to='comics_db.ParserRun')),
            ],
            options={
                'ordering': ['parser_run', '-start'],
                'abstract': False,
            },
        ),
    ]
