# Generated by Django 2.1.7 on 2019-03-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0024_publisher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=models.CharField(max_length=100, unique=True), max_length=500, unique=True),
        ),
    ]
