# Generated by Django 2.2.3 on 2019-07-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0025_auto_20190729_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='possible_matches',
            field=models.ManyToManyField(related_name='db_possible_issues', to='comics_db.MarvelAPIComics'),
        ),
    ]
