# Generated by Django 2.1.7 on 2019-03-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0026_auto_20190311_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='universe',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=500, unique=True),
        ),
    ]
