# Generated by Django 2.1.7 on 2019-03-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0027_auto_20190311_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=500, unique=True),
        ),
    ]
