# Generated by Django 2.2.3 on 2019-07-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0027_auto_20190729_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marvelapiissuemergeparserrundetail',
            name='api_comic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comics_db.MarvelAPIComics'),
        ),
    ]
