# Generated by Django 2.1.7 on 2019-03-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0029_issue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=500, unique=True),
        ),
    ]
