# Generated by Django 2.2.3 on 2019-08-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0029_auto_20190729_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='marvelapiissuemergeparserrundetail',
            name='merge_result',
            field=models.CharField(blank=True, choices=[('ALREADY', 'Already matched'), ('SUCCESS', 'Success'), ('NOT_FOUND', 'Match not found'), ('DUPLICATES', 'Multiple matches'), ('MANUAL', 'Manually changed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marvelapititlemergeparserrundetail',
            name='merge_result',
            field=models.CharField(blank=True, choices=[('ALREADY', 'Already matched'), ('SUCCESS', 'Success'), ('NOT_FOUND', 'Match not found'), ('DUPLICATES', 'Multiple matches'), ('MANUAL', 'Manually changed')], max_length=20),
        ),
    ]
