# Generated by Django 2.2.3 on 2019-08-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0030_auto_20190802_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='url',
            new_name='marvel_url',
        ),
    ]
