# Generated by Django 2.1.7 on 2019-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0030_auto_20190311_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='poster',
            field=models.ImageField(null=True, upload_to='publisher_poster'),
        ),
    ]
