# Generated by Django 2.2.4 on 2019-08-03 21:01

import comics_db.fields
import comics_db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0031_auto_20190802_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to=comics_db.models.get_event_image_name),
        ),
    ]
