# Generated by Django 2.1.7 on 2019-03-11 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0031_publisher_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='character')),
                ('marvel_api_id', models.IntegerField(null=True)),
                ('marvel_detail_link', models.URLField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='IssueCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarvelEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='event-image')),
                ('detail_link', models.URLField(blank=True, max_length=1000)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('characters', models.ManyToManyField(related_name='events', to='comics_db.Character')),
            ],
        ),
        migrations.CreateModel(
            name='TitleCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='creator',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='pencilers',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='writers',
        ),
        migrations.AddField(
            model_name='creator',
            name='marvel_api_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='marvel_api_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='marvel_api_status',
            field=models.CharField(choices=[('NEW', 'New'), ('NO_ID', "Can't find ID"), ('ID_GET_DATA', 'ID found, need to get data'), ('PROCESSED', 'Processed')], default='NEW', max_length=30),
        ),
        migrations.AddField(
            model_name='issue',
            name='marvel_detail_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='issue',
            name='marvel_purchase_link',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='title',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='title',
            name='image',
            field=models.ImageField(null=True, upload_to='title_image'),
        ),
        migrations.AddField(
            model_name='title',
            name='marvel_api_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='marvel_api_status',
            field=models.CharField(choices=[('NEW', 'New'), ('NO_ID', "Can't find ID"), ('ID_GET_DATA', 'ID found, need to get data'), ('PROCESSED', 'Processed')], default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='issue',
            name='main_cover',
            field=models.ImageField(null=True, upload_to='issue_cover'),
        ),
        migrations.AddField(
            model_name='titlecreator',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.Creator'),
        ),
        migrations.AddField(
            model_name='titlecreator',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.Title'),
        ),
        migrations.AddField(
            model_name='marvelevent',
            name='creators',
            field=models.ManyToManyField(related_name='events', to='comics_db.Creator'),
        ),
        migrations.AddField(
            model_name='marvelevent',
            name='issues',
            field=models.ManyToManyField(related_name='events', to='comics_db.Issue'),
        ),
        migrations.AddField(
            model_name='marvelevent',
            name='titles',
            field=models.ManyToManyField(related_name='events', to='comics_db.Title'),
        ),
        migrations.AddField(
            model_name='issuecreator',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.Creator'),
        ),
        migrations.AddField(
            model_name='issuecreator',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.Issue'),
        ),
        migrations.AddField(
            model_name='character',
            name='issues',
            field=models.ManyToManyField(related_name='characters', to='comics_db.Issue'),
        ),
        migrations.AddField(
            model_name='character',
            name='titles',
            field=models.ManyToManyField(related_name='characters', to='comics_db.Title'),
        ),
        migrations.AddField(
            model_name='issue',
            name='creators',
            field=models.ManyToManyField(related_name='issues', through='comics_db.IssueCreator', to='comics_db.Creator'),
        ),
        migrations.AddField(
            model_name='title',
            name='creators',
            field=models.ManyToManyField(related_name='titles', through='comics_db.TitleCreator', to='comics_db.Creator'),
        ),
    ]
