# Generated by Django 2.1.7 on 2019-03-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0032_auto_20190311_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creator',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marvelevent',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='marvelevent',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
