# Generated by Django 2.2.4 on 2019-08-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0032_auto_20190804_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='url',
            new_name='marvel_api_url',
        ),
    ]
