# Generated by Django 2.1.7 on 2019-03-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0034_auto_20190313_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='path_key',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
