# Generated by Django 2.1.7 on 2019-03-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0035_title_path_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='path_key',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
