# Generated by Django 2.1.7 on 2019-03-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0036_auto_20190313_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='poster',
            field=models.ImageField(null=True, upload_to='universe_poster'),
        ),
    ]
