# Generated by Django 2.1.7 on 2019-03-14 21:32

import comics_db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0037_universe_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='main_cover',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to='issue_cover'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to='publisher_logo'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='poster',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to='publisher_poster'),
        ),
        migrations.AlterField(
            model_name='title',
            name='image',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to='title_image'),
        ),
        migrations.AlterField(
            model_name='universe',
            name='poster',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to='universe_poster'),
        ),
    ]
