# Generated by Django 2.2.4 on 2019-08-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0038_auto_20190812_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='marvel_api_ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='title',
            name='marvel_api_ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marvelapiissuemergeparserrundetail',
            name='merge_result',
            field=models.CharField(blank=True, choices=[('ALREADY', 'Already matched'), ('SUCCESS', 'Success'), ('NOT_FOUND', 'Match not found'), ('DUPLICATES', 'Multiple matches'), ('IGNORE', 'Ignored until full API parse'), ('MANUAL', 'Manually changed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='marvelapititlemergeparserrundetail',
            name='merge_result',
            field=models.CharField(blank=True, choices=[('ALREADY', 'Already matched'), ('SUCCESS', 'Success'), ('NOT_FOUND', 'Match not found'), ('DUPLICATES', 'Multiple matches'), ('IGNORE', 'Ignored until full API parse'), ('MANUAL', 'Manually changed')], max_length=20),
        ),
    ]
