# Generated by Django 2.1.7 on 2019-03-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0038_auto_20190315_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='page_count',
            field=models.IntegerField(null=True),
        ),
    ]
