# Generated by Django 2.1.7 on 2019-03-17 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0039_issue_page_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.Issue')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics_db.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='read_issues',
            field=models.ManyToManyField(related_name='readers', through='comics_db.ReadIssue', to='comics_db.Issue'),
        ),
    ]
