# Generated by Django 2.1.7 on 2019-03-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0040_auto_20190318_0104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readissue',
            unique_together={('profile', 'issue')},
        ),
    ]
