# Generated by Django 2.1.7 on 2019-03-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0041_auto_20190318_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserrun',
            name='celery_task_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
