# Generated by Django 2.1.7 on 2019-03-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0042_auto_20190320_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='path_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='title',
            unique_together={('name', 'publisher', 'universe', 'title_type'), ('path_key', 'publisher', 'universe', 'title_type')},
        ),
    ]
