# Generated by Django 2.1.7 on 2019-03-24 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0044_parserrunparams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parserrun',
            name='processed',
        ),
    ]
