# Generated by Django 2.1.7 on 2019-03-24 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0045_remove_parserrun_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parserrunparams',
            name='parser_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='comics_db.ParserRun'),
        ),
    ]
