# Generated by Django 2.1.7 on 2019-03-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0046_auto_20190324_0412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parserrunparams',
            options={'ordering': ['id']},
        ),
    ]
