# Generated by Django 2.1.7 on 2019-04-01 18:34

import comics_db.fields
import comics_db.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0047_auto_20190324_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['title', 'number']},
        ),
        migrations.AlterField(
            model_name='issue',
            name='main_cover',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to=comics_db.models.get_issue_cover_name),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to=comics_db.models.get_publisher_logo_name),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='poster',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to=comics_db.models.get_publisher_poster_name),
        ),
        migrations.AlterField(
            model_name='title',
            name='image',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to=comics_db.models.get_title_image_name),
        ),
        migrations.AlterField(
            model_name='title',
            name='universe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='titles', to='comics_db.Universe'),
        ),
        migrations.AlterField(
            model_name='universe',
            name='poster',
            field=comics_db.fields.ThumbnailImageField(null=True, upload_to=comics_db.models.get_universe_poster_name),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='issues',
            field=models.ManyToManyField(related_name='reading_lists', to='comics_db.Issue'),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to='comics_db.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='readinglist',
            unique_together={('owner', 'name')},
        ),
    ]
