# Generated by Django 2.1.7 on 2019-04-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0048_auto_20190401_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='readinglist',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
