# Generated by Django 2.2 on 2019-04-15 12:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0049_readinglist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marvelapicharacter',
            name='modified',
            field=models.DateTimeField(help_text='The date the resource was most recently modified.', null=True),
        ),
        migrations.AlterField(
            model_name='marvelapicomics',
            name='modified',
            field=models.DateTimeField(help_text='The date the resource was most recently modified.', null=True),
        ),
        migrations.AlterField(
            model_name='marvelapicreator',
            name='modified',
            field=models.DateTimeField(help_text='The date the resource was most recently modified.', null=True),
        ),
        migrations.AlterField(
            model_name='marvelapidate',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='marvelapievent',
            name='modified',
            field=models.DateTimeField(help_text='The date the resource was most recently modified.', null=True),
        ),
        migrations.AlterField(
            model_name='marvelapiseries',
            name='modified',
            field=models.DateTimeField(help_text='The date the resource was most recently modified.', null=True),
        ),
        migrations.AlterField(
            model_name='parserrun',
            name='parser',
            field=models.CharField(choices=[('BASE', 'Base parser'), ('CLOUD_FILES', 'Cloud files parser'), ('MARVEL_API', 'Marvel API parser')], default='BASE', max_length=30),
        ),
        migrations.AlterField(
            model_name='parserrun',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('COLLECTING', 'Collecting data'), ('SUCCESS', 'Successfully ended'), ('ENDED_WITH_ERRORS', 'Ended with errors'), ('API_THROTTLE', 'API rate limit has been surpassed.'), ('CRITICAL_ERROR', 'Critical Error'), ('INVALID_PARSER', 'Invalid parser implementation')], default='RUNNING', max_length=30),
        ),
        migrations.CreateModel(
            name='MarvelAPIParserRunDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('ERROR', 'Error')], default='RUNNING', max_length=30)),
                ('error', models.TextField(blank=True)),
                ('error_detail', models.TextField(blank=True)),
                ('entity_type', models.CharField(choices=[('COMICS', 'Comics'), ('CHARACTER', 'Character'), ('CREATOR', 'Creator'), ('EVENT', 'Event'), ('SERIES', 'Series')], max_length=10)),
                ('action', models.CharField(choices=[('GET', 'Getting data from API'), ('PROCESS', 'Processing data')], max_length=10)),
                ('entity_id', models.IntegerField(null=True)),
                ('data', models.TextField(blank=True)),
                ('parser_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marvelapiparserrundetails', to='comics_db.ParserRun')),
            ],
            options={
                'ordering': ['parser_run', '-start'],
                'abstract': False,
            },
        ),
    ]
