# Generated by Django 2.2 on 2019-04-16 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0050_auto_20190415_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marvelapicomics',
            name='format',
        ),
    ]
