# Generated by Django 2.2 on 2019-04-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0051_remove_marvelapicomics_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marvelapicomics',
            name='creators',
        ),
        migrations.AddField(
            model_name='marvelapiimage',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail', to='comics_db.MarvelAPISeries'),
        ),
        migrations.AddField(
            model_name='marvelapisiteurl',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to='comics_db.MarvelAPISeries'),
        ),
    ]
