# Generated by Django 2.2 on 2019-04-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0052_auto_20190421_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvelapicomics',
            name='creators',
            field=models.ManyToManyField(help_text='Creators associated with this comic.', related_name='comics', through='comics_db.MarvelAPIComicsCreator', to='comics_db.MarvelAPICreator'),
        ),
    ]
