# Generated by Django 2.2 on 2019-04-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0053_marvelapicomics_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marvelapievent',
            name='creators',
        ),
        migrations.RemoveField(
            model_name='marvelapiseries',
            name='creators',
        ),
        migrations.AlterField(
            model_name='parserrun',
            name='status',
            field=models.CharField(choices=[('COLLECTING', 'Collecting data'), ('RUNNING', 'Running'), ('SUCCESS', 'Successfully ended'), ('ENDED_WITH_ERRORS', 'Ended with errors'), ('API_THROTTLE', 'API rate limit has been surpassed.'), ('CRITICAL_ERROR', 'Critical Error'), ('INVALID_PARSER', 'Invalid parser implementation')], default='COLLECTING', max_length=30),
        ),
    ]
