# Generated by Django 2.2 on 2019-04-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics_db', '0054_auto_20190422_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvelapievent',
            name='creators',
            field=models.ManyToManyField(help_text='Creators whose work appears in this event.', related_name='events', through='comics_db.MarvelAPIEventCreator', to='comics_db.MarvelAPICreator'),
        ),
        migrations.AddField(
            model_name='marvelapiseries',
            name='creators',
            field=models.ManyToManyField(help_text='Creators whose work appears in comics in this series.', related_name='series', through='comics_db.MarvelAPISeriesCreator', to='comics_db.MarvelAPICreator'),
        ),
    ]
